name: Email to WhatsApp Scheduler

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run email summary bot
        env:
          EMAIL: ${{ secrets.EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
          ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          TWILIO_NUMBER: ${{ secrets.TWILIO_NUMBER }}
          WHATSAPP_NUMBER: ${{ secrets.WHATSAPP_NUMBER }}
          HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
        run: python main.py
